apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  selector:
    matchLabels:
      io.kompose.service: api-gateway
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: api-gateway
    spec:
      containers:
      - command:
        - ./dockerize
        - -wait=tcp://discovery-server:8761
        - -timeout=60s
        - --
        - java
        - -XX:+UnlockExperimentalVMOptions
        - -XX:+UseCGroupMemoryLimitForHeap
        - -Djava.security.egd=file:/dev/./urandom
        - -jar
        - /app.jar
        image: jkjell/spring-petclinic-api-gateway
        imagePullPolicy: Never
        name: api-gateway
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "536870912"
      restartPolicy: Always
status: {}
