apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus-server
  name: prometheus-server
spec:
  selector:
    matchLabels:
      io.kompose.service: prometheus-server
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: prometheus-server
    spec:
      containers:
      - image: prometheus-server
        name: prometheus-server
        imagePullPolicy: Never
        ports:
        - containerPort: 9090
        resources:
          limits:
            memory: "512M"
      restartPolicy: Always
status: {}
