apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    app: {{ template "spring-petclinic.fullname" . }}-admin-server
    chart: {{ template "spring-petclinic.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  name: {{ template "spring-petclinic.fullname" . }}-admin-server
spec:
  selector:
    matchLabels:
      app: {{ template "spring-petclinic.fullname" . }}-admin-server
      release: {{ .Release.Name | quote }}
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        app: {{ template "spring-petclinic.fullname" . }}-admin-server
        chart: {{ template "spring-petclinic.chart" . }}
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
    spec:
      hostname: {{ template "spring-petclinic.fullname" . }}-admin-server
      containers:
      - command:
        - ./dockerize
        - -wait=tcp://discovery-server:8761
        - -timeout=60s
        - --
        - java
        - -XX:+UnlockExperimentalVMOptions
        - -XX:+UseCGroupMemoryLimitForHeap
        - -Djava.security.egd=file:/dev/./urandom
        - -jar
        - /app.jar
{{ $imageInfo := (dict "image" .Values.images.admin_server "global" .Values.global) }}
{{ include "imagePullSecrets" $imageInfo | indent 8 }}
        image: {{ include "registryImage" $imageInfo }}
        imagePullPolicy: {{ include "imagePullPolicy" $imageInfo }}
        name: {{ template "spring-petclinic.fullname" . }}-admin-server
        ports:
        - containerPort: 9090
        resources:
          limits:
            memory: "512M"
      restartPolicy: Always
status: {}
