apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: admin-server
  name: admin-server
spec:
  selector:
    matchLabels:
      io.kompose.service: admin-server
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: admin-server
    spec:
      hostname: admin-server
      containers:
      - command:
        - ./dockerize
        - -wait=tcp://discovery-server:8761
        - -timeout=60s
        - --
        - java
        - -XX:+UnlockExperimentalVMOptions
        - -XX:+UseCGroupMemoryLimitForHeap
        - -Djava.security.egd=file:/dev/./urandom
        - -jar
        - /app.jar
        image: jkjell/spring-petclinic-admin-server
        imagePullPolicy: Never
        name: admin-server
        ports:
        - containerPort: 9090
        resources:
          limits:
            memory: "512M"
      restartPolicy: Always
status: {}
