apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    springPetclinic.version: {{ .Values.springPetclinic.version }}
  creationTimestamp: null
  name: {{ template "spring-petclinic.fullname" . }}-api-gateway
  labels:
    app: {{ template "spring-petclinic.fullname" . }}-api-gateway
    chart: {{ template "spring-petclinic.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{ template "spring-petclinic.labels" | indent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "spring-petclinic.fullname" . }}-api-gateway
      chart: {{ template "spring-petclinic.chart" . }}
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        springPetclinic.version: {{ .Values.springPetclinic.version }}
      creationTimestamp: null
      labels:
        app: {{ template "spring-petclinic.fullname" . }}-api-gateway
        chart: {{ template "spring-petclinic.chart" . }}
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
{{ template "spring-petclinic.labels" | indent 8 }}
    spec:
      containers:
      - command:
        - ./dockerize
        - -wait=tcp://discovery-server:8761
        - -timeout=60s
        - --
        - java
        - -XX:+UnlockExperimentalVMOptions
        - -XX:+UseCGroupMemoryLimitForHeap
        - -Djava.security.egd=file:/dev/./urandom
        - -jar
        - /app.jar
{{ $imageInfo := (dict "image" .Values.images.api_gateway "global" .Values.global) }}
{{ include "imagePullSecrets" $imageInfo | indent 8 }}
        image: {{ include "registryImage" $imageInfo }}
        imagePullPolicy: {{ include "imagePullPolicy" $imageInfo }}
        name: {{ template "spring-petclinic.fullname" . }}-api-gateway
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "536870912"
      restartPolicy: Always
status: {}
