apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    app: {{ template "spring-petclinic.name" . }}-api-gateway
    chart: {{ template "spring-petclinic.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  name: {{ template "spring-petclinic.name" . }}-api-gateway
spec:
  ports:
  - name: {{ template "spring-petclinic.name" . }}-api-gateway
    port: 8080
    targetPort: {{ template "spring-petclinic.name" . }}-api-gateway
  selector:
    io.kompose.service: api-gateway
status:
  loadBalancer: {}
