apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    springPetclinic.version: {{ .Values.springPetclinic.version }}
  creationTimestamp: null
  labels:
    app: {{ template "spring-petclinic.fullname" . }}-config-server
    chart: {{ template "spring-petclinic.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{ template "spring-petclinic.labels" | indent 4 }}
  name: {{ template "spring-petclinic.fullname" . }}-config-server
spec:
  selector:
    matchLabels:
      app: {{ template "spring-petclinic.fullname" . }}-config-server
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        springPetclinic.version: {{ .Values.springPetclinic.version }}
      creationTimestamp: null
      labels:
        app: {{ template "spring-petclinic.fullname" . }}-config-server
        chart: {{ template "spring-petclinic.chart" . }}
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
{{ template "spring-petclinic.labels" | indent 8 }}
    spec:
      containers:
      - name: {{ template "spring-petclinic.fullname" . }}-config-server
{{ $imageInfo := (dict "image" .Values.images.config_server "global" .Values.global) }}
{{ include "imagePullSecrets" $imageInfo | indent 8 }}
        image: {{ include "registryImage" $imageInfo }}
        imagePullPolicy: {{ include "imagePullPolicy" $imageInfo }}
        ports:
        - containerPort: 8888
        resources:
          limits:
            memory: "536870912"
      restartPolicy: Always
status: {}
