apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    springPetclinic.version: {{ .Values.springPetclinic.version }}
  creationTimestamp: null
  labels:
{{ include "spring-petclinic.labels" . | indent 4 }}
    app: {{ template "spring-petclinic.fullname" . }}-grafana-server
    chart: {{ template "spring-petclinic.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  name: {{ template "spring-petclinic.fullname" . }}-grafana-server
spec:
  selector:
    matchLabels:
      app: {{ template "spring-petclinic.fullname" . }}-grafana-server
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        springPetclinic.version: {{ .Values.springPetclinic.version }}
      creationTimestamp: null
      labels:
{{ include "spring-petclinic.labels" . | indent 8 }}
        app: {{ template "spring-petclinic.fullname" . }}-grafana-server
        chart: {{ template "spring-petclinic.chart" . }}
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
    spec:
      containers:
      - name: {{ template "spring-petclinic.fullname" . }}-grafana-server
{{ $imageInfo := (dict "image" .Values.images.grafana_server "global" .Values.global) }}
        image: {{ include "registryImage" $imageInfo }}
        imagePullPolicy: {{ include "imagePullPolicy" $imageInfo }}
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 3000
        env:
        - name: PROMETHEUS_SERVER_SVC
          value: "{{ template "spring-petclinic.fullname" . }}-prometheus-server"
        resources:
          limits:
            memory: "256M"
{{ include "imagePullSecrets" $imageInfo | indent 6 }}
      restartPolicy: Always
status: {}
