apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    app: {{ template "spring-petclinic.name" . }}-grafana-server
    chart: {{ template "spring-petclinic.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  name: {{ template "spring-petclinic.name" . }}-grafana-server
spec:
  selector:
    matchLabels:
      app: {{ template "spring-petclinic.name" . }}-grafana-server
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        app: {{ template "spring-petclinic.name" . }}-grafana-server
        chart: {{ template "spring-petclinic.chart" . }}
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
    spec:
      containers:
      - name: {{ template "spring-petclinic.name" . }}-grafana-server
{{ $imageInfo := (dict "image" .Values.images.discovery_server "global" .Values.global) }}
{{ include "imagePullSecrets" $concourseImage | indent 8 }}
        image: {{ include "registryImage" $imageInfo }}
        imagePullPolicy: {{ include "imagePullPolicy" $imageInfo }}
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "256M"
      restartPolicy: Always
status: {}
