apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    app: {{ template "spring-petclinic.fullname" . }}-prometheus-server
    chart: {{ template "spring-petclinic.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  name: {{ template "spring-petclinic.fullname" . }}-prometheus-server
spec:
  ports:
  - port: 9091
  selector:
    app: {{ template "spring-petclinic.fullname" . }}-prometheus-server
status:
  loadBalancer: {}
