apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus-server
  name: prometheus-server
spec:
  ports:
  - name: {{ template "spring-petclinic.name" . }}-prometheus-server
    port: 9091
    targetPort: {{ template "spring-petclinic.name" . }}-prometheus-server
  selector:
    io.kompose.service: prometheus-server
status:
  loadBalancer: {}
