apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    springPetclinic.version: {{ .Values.springPetclinic.version }}
  creationTimestamp: null
  labels:
{{ template "spring-petclinic.labels" | indent 4 }}
    app: {{ template "spring-petclinic.fullname" . }}-tracing-server
    chart: {{ template "spring-petclinic.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  name: {{ template "spring-petclinic.fullname" . }}-tracing-server
spec:
  selector:
    matchLabels:
      app: {{ template "spring-petclinic.fullname" . }}-tracing-server
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        springPetclinic.version: {{ .Values.springPetclinic.version }}
      creationTimestamp: null
      labels:
{{ template "spring-petclinic.labels" | indent 8 }}
        app: {{ template "spring-petclinic.fullname" . }}-tracing-server
        chart: {{ template "spring-petclinic.chart" . }}
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
{{ $imageInfo := (dict "image" .Values.images.tracing_server "global" .Values.global) }}
{{ include "imagePullSecrets" $imageInfo | indent 8 }}
        image: {{ include "registryImage" $imageInfo }}
        imagePullPolicy: {{ include "imagePullPolicy" $imageInfo }}
        name: {{ template "spring-petclinic.fullname" . }}-tracing-server
        ports:
        - containerPort: 9411
        resources:
          limits:
            memory: "512M"
      restartPolicy: Always
status: {}
