apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: tracing-server
  name: tracing-server
spec:
  ports:
  - name: {{ template "spring-petclinic.name" . }}-tracing-server
    port: 9411
    targetPort: {{ template "spring-petclinic.name" . }}-tracing-server
  selector:
    io.kompose.service: tracing-server
status:
  loadBalancer: {}
