apiVersion: v1
kind: Service
metadata:
  annotations:
    springPetclinic.version: {{ .Values.springPetclinic.version }}
  creationTimestamp: null
  labels:
{{ include "spring-petclinic.labels" . | indent 4 }}
    app: {{ template "spring-petclinic.fullname" . }}-vets-service
    chart: {{ template "spring-petclinic.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  name: {{ template "spring-petclinic.fullname" . }}-vets-service
spec:
  ports:
  - port: 8083
  selector:
    app: {{ template "spring-petclinic.fullname" . }}-vets-service
status:
  loadBalancer: {}
