apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: vets-service
  name: vets-service
spec:
  ports:
  - name: {{ template "spring-petclinic.name" . }}-vets-service
    port: 8083
    targetPort: {{ template "spring-petclinic.name" . }}-vets-service
  selector:
    io.kompose.service: vets-service
status:
  loadBalancer: {}
