apiVersion: v1
kind: Service
metadata:
  annotations:
    springPetclinic.version: {{ .Values.springPetclinic.version }}
  creationTimestamp: null
  labels:
{{ template "spring-petclinic.labels" | indent 4 }}
    app: {{ template "spring-petclinic.fullname" . }}-visits-service
    chart: {{ template "spring-petclinic.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  name: {{ template "spring-petclinic.fullname" . }}-visits-service
spec:
  ports:
  - port: 8082
  selector:
    app: {{ template "spring-petclinic.fullname" . }}-visits-service
status:
  loadBalancer: {}
