apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: visits-service
  name: visits-service
spec:
  ports:
  - name: {{ template "spring-petclinic.name" . }}-visits-service
    port: 8082
    targetPort: {{ template "spring-petclinic.name" . }}-visits-service
  selector:
    io.kompose.service: visits-service
status:
  loadBalancer: {}
