apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    springPetclinic.version: {{ .Values.springPetclinic.version }}
  creationTimestamp: null
  labels:
{{ include "spring-petclinic.labels" . | indent 4 }}
    app: {{ template "spring-petclinic.fullname" . }}-visits-service
    chart: {{ template "spring-petclinic.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  name: {{ template "spring-petclinic.fullname" . }}-visits-service
spec:
  selector:
    matchLabels:
      app: {{ template "spring-petclinic.fullname" . }}-visits-service
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        springPetclinic.version: {{ .Values.springPetclinic.version }}
      creationTimestamp: null
      labels:
{{ include "spring-petclinic.labels" . | indent 8 }}
        app: {{ template "spring-petclinic.fullname" . }}-visits-service
        chart: {{ template "spring-petclinic.chart" . }}
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
    spec:
      hostname: {{ template "spring-petclinic.fullname" . }}-visits-service
      containers:
      - command:
        - ./dockerize
        - -wait=tcp://{{ template "spring-petclinic.fullname" . }}-discovery-server:8761
        - -timeout=60s
        - --
        - java
        - -XX:+UnlockExperimentalVMOptions
        - -XX:+UseContainerSupport
        - -Djava.security.egd=file:/dev/./urandom
        - -Dspring.cloud.config.uri=http://{{ template "spring-petclinic.fullname" . }}-config-server:8888
        - -Deureka.client.serviceUrl.defaultZone=http://{{ template "spring-petclinic.fullname" . }}-discovery-server:8761/eureka/
        - -jar
        - /app.jar
{{ $imageInfo := (dict "image" .Values.images.visits_service "global" .Values.global) }}
        image: {{ include "registryImage" $imageInfo }}
        imagePullPolicy: {{ include "imagePullPolicy" $imageInfo }}
        name: {{ template "spring-petclinic.fullname" . }}-visits-service
        ports:
        - containerPort: 8082
        resources:
          limits:
            memory: "512M"
{{ include "imagePullSecrets" $imageInfo | indent 6 }}
      restartPolicy: Always
status: {}
